### ISSUE TITLE
Codebase is not updated

### ISSUE THREAD

**Issue by tutcake** [minhtc/audiobookapp#13]
The UI and code of production version app in Playstore seems to be different to what is available here. When will you update the code.

Love your work btw.

**Comment by minhtc** [comment]
> The UI and code of production version app in Playstore seems to be different to what is available here. When will you update the code.
> 
> Love your work btw.

The production version is totally different from the open-sourced version. 
It is very complex and I can't share it currently. Please be understand.

**Comment by tutcake** [comment]
Ok, I understand and respect your decision. Thank you. You can close this issue now.
