### ISSUE TITLE
can not build android

### ISSUE THREAD

**Issue by mahmed0715** [minhtc/audiobookapp#4]
Hi,  I was not able to build for android.
![Screenshot from 2019-12-03 13-36-57](https://user-images.githubusercontent.com/2967789/70029773-00dcb080-15d2-11ea-8709-4b702a45c07e.png)
tia

**Comment by minhtc** [comment]
> Hi, I was not able to build for android.
> ![Screenshot from 2019-12-03 13-36-57](https://user-images.githubusercontent.com/2967789/70029773-00dcb080-15d2-11ea-8709-4b702a45c07e.png)
> tia

Thank you for reporting, I will have a look now

**Comment by minhtc** [comment]
@mahmed0715 still build success in my side, seem like you did change something, try to remove all codes and clone app into a new folder

**Comment by abdulsamadola** [comment]
@minhtc  I'm having the same issues, while trying to build for android. Is there any way out? Thanks

**Comment by abdulsamadola** [comment]
> @minhtc I'm having the same issues, while trying to build for android. Is there any way out? Thanks

Fixed the issues by upgrading to androidx. [click here to find out](https://developer.android.com/jetpack/androidx/migrate)

**Comment by abdulsamadola** [comment]
> Hi, I was not able to build for android.
> ![Screenshot from 2019-12-03 13-36-57](https://user-images.githubusercontent.com/2967789/70029773-00dcb080-15d2-11ea-8709-4b702a45c07e.png)
> tia

Fixed the issues by upgrading to androidx. [click here to find out](https://developer.android.com/jetpack/androidx/migrate)

**Comment by minhtc** [comment]
Sorry for the delay. The app has been upgraded to the latest react-native version 0.62.2

**Comment by abdulsamadola** [comment]
@minhtc Thanks for the upgrade. Cheers!

> Sorry for the delay. The app has been upgraded to the latest react-native version 0.62.2
