### ISSUE TITLE
Dou you think upgrade this app

### ISSUE THREAD

**Issue by mustafat0k** [minhtc/audiobookapp#5]
Pretty good application i appreciate you. Do you think upgrade this repo because many things deprecated in app.

**Comment by minhtc** [comment]
> Pretty good application i appreciate you. Do you think upgrade this repo because many things deprecated in app.

Yeap I will upgrade in next few days...

**Comment by minhtc** [comment]
Sorry for the delay. The app has been upgraded to the latest react-native version 0.62.2
